### ISSUE TITLE
Create `useWindow` and `useDocument` hooks

### ISSUE THREAD

**Issue by leroykorterink** [mediamonks/react-hooks#101]
See title

```ts
function useWindow(): (Window & typeof globalThis) | undefined {
  return typeof window === 'undefined' ? window : undefined;
}
```

```ts
function useDocument(): Document | undefined {
  return typeof document === 'undefined' ? document : undefined;
}
```

The `useWindowEVentListener` and `useDocumentEventListener` hooks can be removed when these hooks are added. The `useEventListener` hook should be used to add listeners to the `window` and `document`.

e.g.

```ts
function useMyHook() {
  const window = useWindow();
  
  const onWindowResize = useRafCallback(() => {
    console.log("I'm called on resize")
  }, []);

  useEventListener(window, 'resize', onWindowResize);
}
```

**Comment by jesse-mm** [comment]
Isn't it possible to handle within the `useEventListener` hook automatically ? This feels a bit cumbersome.

**Comment by ThaNarie** [comment]
It's not, since referencing `window` or `document` directly, without a `typeof`, will give an error in node.

**Comment by jesse-mm** [comment]
Yes I know but can't we move that specific check to the hook itself.. That is what I meant. You would always attach to an object type right ?. When hydration is happening the hook will have to 'window' or 'document' references.

**Comment by jesse-mm** [comment]
@ThaNarie What about passing `global.window` or `global.document` directly ?

**Comment by leroykorterink** [comment]
I didn't know `window` and `document` are properties of the `global` object! But we should use `globalThis` instead of `global` because it's be more reliable in different environments.

We should definitely use the fields from the `globalThis` object instead of using the hooks.
