### ISSUE TITLE
Create `createTimeout` util

### ISSUE THREAD

**Issue by leroykorterink** [mediamonks/react-hooks#119]
Create a function that resolves after given timeout.

```ts
function waitForTimeout(ms = 0): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}
```

**Comment by leroykorterink** [comment]
@ThaNarie I don't know if this package is the right place to add this because it's a generic utility that can be useful in any project.

**Comment by jesse-mm** [comment]
I've been calling this one `sleep` 😴  `await sleep(2000)` but this naming is better!
