### ISSUE TITLE
Add integration tests using a real browser

### ISSUE THREAD

**Issue by leroykorterink** [mediamonks/react-hooks#57]
The JSDom doesn't expose all APIs that we use in the project so we cannot write automated test for certain hooks right now. We can use e.g. cypress to test these hooks but https://playwright.dev/docs/test-components is also something worth investigating.

**Comment by ThaNarie** [comment]
Alternative would be to use mock/polyfill implementations, but playwright looks good!

I believe storybook test runner uses playwright to test their "play" tests in CI, so using stories to tests those might be another feature.
