### ISSUE TITLE
Default React Portal component?

### ISSUE THREAD

**Issue by ReneDrie** [mediamonks/react-hooks#67]
Should we create a simple React Portal component? Since we're adding some components it could be very useful to have 1 proper implementation for this I guess? This way it's easy for people to use and I think it will be used more than the AutoFill component.

We could also see if it should just be added to the skeleton by default, but this could also be a good place

**Comment by ThaNarie** [comment]
I checked 2 popular portal libraries earlier, and both didn't offer some basic functionality that I think we want (related to providers and stuff), so having our own version isn't that bad.

**Comment by leroykorterink** [comment]
I think we should have something like this somewhere but I don't know if it should be part of this package. A portal/overlay needs styling and that is imo not something we should expose via this package.

**Comment by ReneDrie** [comment]
I don't think this should contain any styling as well. But just the functionality of a portal is fine.

**Comment by leroykorterink** [comment]
> I don't think this should contain any styling as well. But just the functionality of a portal is fine.

What exactly should a portal component do according to you? I think we need two hooks to make it easier to create portals, but I'm not sure if we need a component for it.

- `useWindowScrollLock`
- `useFocusLock`

The focus and scroll lock are not always needed. With the 2 hooks it'll be easy to make an accessible Portal.

```tsx
const MyPortal = ensuredForwardRef((props, ref): ReactNode => {
  useWindowScrollLock();
  useFocusLock(ref);

  return (
    <>
      {createPortal(
        <div ref={ref}>My portal content</div>,
        document.querySelector("#portal")
      )}
    </>
  );
});
```

**Comment by jesse-mm** [comment]
@leroykorterink For me a portal is a portal, the things like `focusLock` and `useWindowScrollLock` to me are implementation details (especially `useWindowScrollLock`). A portal in essence is just a place where things get rendered. 

I'm trying to figure what we are trying to achieve here, do we want some kind of "Modal" implementation?

**Comment by leroykorterink** [comment]
Yeah I agree @jesse-mm. I think the `createPortal` API in React already does what @ReneDrie proposes, we don't need to wrap it in a custom component.

**Comment by ReneDrie** [comment]
I didn't knew abvout the `createPortal` method, this was just about that. For another project I did some of my own implementation that's why I thought it could be handy. 
So with that I think this ticket can be closed

**Comment by leroykorterink** [comment]
We have a solution for this in our foundation right now as far as I know
